CREATE TABLE dbo.BoMon (
    MaBM   VARCHAR(50)  NOT NULL,
    tenBM  VARCHAR(50)  NULL,
    maKhoa VARCHAR(10)  NULL, 
    CONSTRAINT PK_BoMon PRIMARY KEY CLUSTERED (MaBM)
);
GO
ALTER TABLE dbo.BoMon  
ADD CONSTRAINT FK_BoMon_Khoa FOREIGN KEY (maKhoa)  
REFERENCES dbo.Khoa (maKhoa);
GO
IF OBJECT_ID('dbo.BoMon', 'U') IS NOT NULL  
    DROP TABLE dbo.BoMon;  
GO  IF OBJECT_ID('dbo.DKMH', 'U') IS NOT NULL
    DROP TABLE dbo.DKMH;
GO

IF OBJECT_ID('dbo.SinhVien', 'U') IS NOT NULL
    DROP TABLE dbo.SinhVien;
GO

CREATE TABLE dbo.SinhVien (
    masv VARCHAR(50) NOT NULL PRIMARY KEY,
    hoTen NVARCHAR(100) NOT NULL
);
GO

CREATE TABLE dbo.DKMH (
    maLopHP VARCHAR(50) NOT NULL,
    maSV VARCHAR(50) NOT NULL,
    DiemTP FLOAT NULL,
    DiemThi FLOAT NULL,
    PhanTramThi FLOAT NULL,
    CONSTRAINT PK_DKMH PRIMARY KEY CLUSTERED (maLopHP, maSV)
);
GO

ALTER TABLE dbo.DKMH ALTER COLUMN maSV VARCHAR(50) NOT NULL;
ALTER TABLE dbo.SinhVien ALTER COLUMN masv VARCHAR(50) NOT NULL;
GO

ALTER TABLE dbo.DKMH 
ADD CONSTRAINT FK_DKMH_SinhVien 
FOREIGN KEY (maSV) REFERENCES dbo.SinhVien(masv);
GO
