CREATE TABLE dbo.GVCN (
    maLop VARCHAR(10) NOT NULL,  
    maGV VARCHAR(50) NOT NULL,  
    HK INT NOT NULL,
    CONSTRAINT PK_GVCN PRIMARY KEY CLUSTERED (maLop, maGV, HK)
);
GO
ALTER TABLE dbo.GVCN 
ADD CONSTRAINT FK_GVCN_Lop 
FOREIGN KEY (maLop) 
REFERENCES dbo.Lop(maLop);
GO

ALTER TABLE dbo.GVCN 
ADD CONSTRAINT FK_GVCN_GiaoVien 
FOREIGN KEY (maGV) 
REFERENCES dbo.GiaoVien(maGV);
GO
IF OBJECT_ID('dbo.GVCN', 'U') IS NOT NULL
    DROP TABLE dbo.GVCN;
GO
