CREATE TABLE [dbo].[LopHP](
	[maLopHP] [varchar](50) NOT NULL,
	[TenLopHP] [nvarchar](50) NULL,
	[HK] [int] NULL,
	[maMon] [varchar](50) NULL,
	[maGV] [varchar](50) NULL,
 CONSTRAINT [PK_LopHP] PRIMARY KEY CLUSTERED 
(
	[maLopHP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_GiaoVien] FOREIGN KEY([maGV])
REFERENCES [dbo].[GiaoVien] ([magv])
GO

ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_GiaoVien]
GO

ALTER TABLE [dbo].[LopHP]  WITH CHECK ADD  CONSTRAINT [FK_LopHP_LopHP] FOREIGN KEY([maLopHP])
REFERENCES [dbo].[LopHP] ([maLopHP])
GO

ALTER TABLE [dbo].[LopHP] CHECK CONSTRAINT [FK_LopHP_LopHP]
GO
IF OBJECT_ID('dbo.LopHP', 'U') IS NOT NULL
    DROP TABLE dbo.LopHP;
GO


